name = "DMRJtensor"
uuid = "5b179a51-5399-4802-8f6e-f7014fc12e6f"
authors = ["Thomas E. Baker"]
version = "0.10.7"

[compat]
julia = "1.8.3"
TensorPACK = "0.3.8"

[deps]
TensorPACK = "31531b1e-8b04-434d-b24f-20dc49cbf098"
